services:
  - name: cloud-app
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    repo: git@github.com:ItchirMaissa/Render_Blueprint.git
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud_db
          property: connectionString

databases:
  - name: cloud_db
    plan: free
    region: frankfurt

